@HangFire_HostAddress = http://localhost:5219

GET {{HangFire_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{HangFire_HostAddress}}/job/createBackgroundJob
Accept: application/json

###
POST {{HangFire_HostAddress}}/job/scheduleJob
Accept: application/json

###
POST {{HangFire_HostAddress}}/job/ContinousJob
Accept: application/json

###
POST {{HangFire_HostAddress}}/job/recurringJob
Accept: application/json